<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#imageio" data-toc-modified-id="imageio-1">imageio</a></span></li><li><span><a href="#Images-as-arrays" data-toc-modified-id="Images-as-arrays-2">Images as arrays</a></span></li></ul></div>

In [1]:
import os

os.chdir('examples')

# Images

In this lesson, we will learn a bit about how computers represent images, and how we can use Python to manipulate image files.

Before you start reading, it may be an interesting exercise to think about how a computer might store an image. As we learned in the [lesson on files](files.ipynb#Encodings), in order to store information computers require some system for converting that information into numbers. How might an image be converted into numbers?

As it turns out, there are a few different ways of turning an image into numbers. We will focus on the most common of these. To find out what it is, let's simply load an image into Python and explore the result. Take a look at the example image file [street_scene.jpg](examples/data/street_scene.jpg). This is the image that it contains:

![](examples/data/street_scene.jpg)

## imageio

There are a few ways to load image files into Python, but the `imageio` [package](extras/glossary.ipynb#package) provides the simplest. (The 'io' in `imageio` stands for [input/output](extras/glossary.ipynb#io).)

Like all the additional Python packages that we have used so far, `imageio` is included in the default Anaconda installation, so if you installed Anaconda then you will already have it.

The `imread()` function reads an image file. The input [argument](extras/glossary.ipynb#argument) to `imread()` is the [path](extras/glossary.ipynb#path) to the file:

In [2]:
import os
import imageio

filepath = os.path.join('data', 'street_scene.jpg')
img = imageio.imread(filepath)

## Images as arrays

So now we can explore the [return value](extras/glossary.ipynb#return) of `imread()`. What sort of object did we get?

The first thing we can do to find out is print the result:

In [3]:
print(img)

[[[217 208 209]
  [216 207 208]
  [215 206 207]
  ...
  [ 76  71  75]
  [ 82  77  81]
  [ 85  79  83]]

 [[217 208 209]
  [216 207 208]
  [216 207 208]
  ...
  [ 77  72  76]
  [ 82  77  81]
  [ 84  78  82]]

 [[217 209 207]
  [217 209 207]
  [218 210 208]
  ...
  [ 79  74  78]
  [ 83  78  82]
  [ 84  78  82]]

 ...

 [[171 163 117]
  [168 161 117]
  [162 155 113]
  ...
  [ 69  75  87]
  [ 72  76  88]
  [ 75  78  93]]

 [[162 157 115]
  [159 154 112]
  [154 149 111]
  ...
  [ 69  75  87]
  [ 71  75  87]
  [ 75  78  93]]

 [[149 144 104]
  [148 145 104]
  [147 143 106]
  ...
  [ 68  75  85]
  [ 72  76  88]
  [ 76  79  94]]]


This looks a lot like an [array](extras/glossary.ipynb#array). Our image has indeed been turned into an array, as we can see from its [type](extras/glossary.ipynb#type):

In [4]:
type(img)

imageio.core.util.Array

We are told that it is an `imageio` array rather than a `numpy` array, but this distinction need not concern us here. Our image is essentially a `numpy` array, and everything that we learned about `numpy` arrays in the [lesson on arrays](arrays.ipynb) also applies to our image array.

For example, the image array has a `shape` [attribute](extras/glossary.ipynb#attribute):

In [5]:
img.shape

(4000, 3000, 3)